package com.louiscad.splitties

object Splitties {
    val pack = Packs

    private const val artifactPrefix = "com.louiscad.splitties:splitties"
    private const val placeholderVersion = "_"

    object Packs {
        const val androidBase = "$artifactPrefix-fun-pack-android-base:$placeholderVersion"
        const val androidBaseWithViewsDsl = "$artifactPrefix-fun-pack-android-base-with-views-dsl:$placeholderVersion"
        const val appCompat = "$artifactPrefix-fun-pack-android-appcompat:$placeholderVersion"
        const val appCompatWithViewsDsl = "$artifactPrefix-fun-pack-android-appcompat-with-views-dsl:$placeholderVersion"
        const val androidMdc = "$artifactPrefix-fun-pack-android-material-components:$placeholderVersion"
        const val androidMdcWithViewsDsl = "$artifactPrefix-fun-pack-android-material-components-with-views-dsl:$placeholderVersion"
    }

    const val activities = "$artifactPrefix-activities:$placeholderVersion"
    const val alertdialog = "$artifactPrefix-alertdialog:$placeholderVersion"
    const val alertdialogAppcompat = "$artifactPrefix-alertdialog-appcompat:$placeholderVersion"
    const val alertdialogAppcompatCoroutines = "$artifactPrefix-alertdialog-appcompat-coroutines:$placeholderVersion"
    const val appctx = "$artifactPrefix-appctx:$placeholderVersion"
    const val archLifecycle = "$artifactPrefix-arch-lifecycle:$placeholderVersion"
    const val archRoom = "$artifactPrefix-arch-room:$placeholderVersion"
    const val bitflags = "$artifactPrefix-bitflags:$placeholderVersion"
    const val bundle = "$artifactPrefix-bundle:$placeholderVersion"
    const val checkedlazy = "$artifactPrefix-checkedlazy:$placeholderVersion"
    const val collections = "$artifactPrefix-collections:$placeholderVersion"
    const val dimensions = "$artifactPrefix-dimensions:$placeholderVersion"
    const val exceptions = "$artifactPrefix-exceptions:$placeholderVersion"
    const val fragments = "$artifactPrefix-fragments:$placeholderVersion"
    const val fragmentargs = "$artifactPrefix-fragmentargs:$placeholderVersion"
    const val initprovider = "$artifactPrefix-initprovider:$placeholderVersion"
    const val intents = "$artifactPrefix-intents:$placeholderVersion"
    const val lifecycleCoroutines = "$artifactPrefix-lifecycle-coroutines:$placeholderVersion"
    const val mainhandler = "$artifactPrefix-mainhandler:$placeholderVersion"
    const val mainthread = "$artifactPrefix-mainthread:$placeholderVersion"
    const val materialColors = "$artifactPrefix-material-colors:$placeholderVersion"
    const val materialLists = "$artifactPrefix-material-lists:$placeholderVersion"
    const val permissions = "$artifactPrefix-permissions:$placeholderVersion"
    const val preferences = "$artifactPrefix-preferences:$placeholderVersion"
    const val resources = "$artifactPrefix-resources:$placeholderVersion"
    const val snackbar = "$artifactPrefix-snackbar:$placeholderVersion"
    const val stethoInit = "$artifactPrefix-stetho-init:$placeholderVersion"
    const val systemservices = "$artifactPrefix-systemservices:$placeholderVersion"
    const val toast = "$artifactPrefix-toast:$placeholderVersion"
    const val typesaferecyclerview = "$artifactPrefix-typesaferecyclerview:$placeholderVersion"
    const val views = "$artifactPrefix-views:$placeholderVersion"
    const val viewsAppcompat = "$artifactPrefix-views-appcompat:$placeholderVersion"
    const val viewsCardview = "$artifactPrefix-views-cardview:$placeholderVersion"
    const val viewsCoroutines = "$artifactPrefix-views-coroutines:$placeholderVersion"
    const val viewsCoroutinesMaterial = "$artifactPrefix-views-coroutines-material:$placeholderVersion"
    const val viewsDsl = "$artifactPrefix-views-dsl:$placeholderVersion"
    const val viewsDslAppcompat = "$artifactPrefix-views-dsl-appcompat:$placeholderVersion"
    const val viewsDslConstraintlayout = "$artifactPrefix-views-dsl-constraintlayout:$placeholderVersion"
    const val viewsDslCoordinatorlayout = "$artifactPrefix-views-dsl-coordinatorlayout:$placeholderVersion"
    const val viewsDslIdePreview = "$artifactPrefix-views-dsl-ide-preview:$placeholderVersion"
    const val viewsDslMaterial = "$artifactPrefix-views-dsl-material:$placeholderVersion"
    const val viewsDslRecyclerview = "$artifactPrefix-views-dsl-recyclerview:$placeholderVersion"
    const val viewsMaterial = "$artifactPrefix-views-material:$placeholderVersion"
    const val viewsRecyclerview = "$artifactPrefix-views-recyclerview:$placeholderVersion"
    const val viewsSelectable = "$artifactPrefix-views-selectable:$placeholderVersion"
    const val viewsSelectableAppcompat = "$artifactPrefix-views-selectable-appcompat:$placeholderVersion"
    const val viewsSelectableConstraintlayout = "$artifactPrefix-views-selectable-constraintlayout:$placeholderVersion"

}
