package com.louiscad.splitties

object Splitties {
    val pack = Packs

    private const val artifactPrefix = "com.louiscad.splitties:splitties"
    private const val versionPlaceholder = "_"

    object Packs {
        const val androidBase = "$artifactPrefix-fun-pack-android-base:$versionPlaceholder"
        const val androidBaseWithViewsDsl = "$artifactPrefix-fun-pack-android-base-with-views-dsl:$versionPlaceholder"
        const val appCompat = "$artifactPrefix-fun-pack-android-appcompat:$versionPlaceholder"
        const val appCompatWithViewsDsl = "$artifactPrefix-fun-pack-android-appcompat-with-views-dsl:$versionPlaceholder"
        const val androidMdc = "$artifactPrefix-fun-pack-android-material-components:$versionPlaceholder"
        const val androidMdcWithViewsDsl = "$artifactPrefix-fun-pack-android-material-components-with-views-dsl:$versionPlaceholder"
    }

    const val activities = "$artifactPrefix-activities:$versionPlaceholder"
    const val alertdialog = "$artifactPrefix-alertdialog:$versionPlaceholder"
    const val alertdialogAppcompat = "$artifactPrefix-alertdialog-appcompat:$versionPlaceholder"
    const val alertdialogAppcompatCoroutines = "$artifactPrefix-alertdialog-appcompat-coroutines:$versionPlaceholder"
    const val appctx = "$artifactPrefix-appctx:$versionPlaceholder"
    const val archLifecycle = "$artifactPrefix-arch-lifecycle:$versionPlaceholder"
    const val archRoom = "$artifactPrefix-arch-room:$versionPlaceholder"
    const val bitflags = "$artifactPrefix-bitflags:$versionPlaceholder"
    const val bundle = "$artifactPrefix-bundle:$versionPlaceholder"
    const val checkedlazy = "$artifactPrefix-checkedlazy:$versionPlaceholder"
    const val collections = "$artifactPrefix-collections:$versionPlaceholder"
    const val dimensions = "$artifactPrefix-dimensions:$versionPlaceholder"
    const val exceptions = "$artifactPrefix-exceptions:$versionPlaceholder"
    const val fragments = "$artifactPrefix-fragments:$versionPlaceholder"
    const val fragmentargs = "$artifactPrefix-fragmentargs:$versionPlaceholder"
    const val initprovider = "$artifactPrefix-initprovider:$versionPlaceholder"
    const val intents = "$artifactPrefix-intents:$versionPlaceholder"
    const val lifecycleCoroutines = "$artifactPrefix-lifecycle-coroutines:$versionPlaceholder"
    const val mainhandler = "$artifactPrefix-mainhandler:$versionPlaceholder"
    const val mainthread = "$artifactPrefix-mainthread:$versionPlaceholder"
    const val materialColors = "$artifactPrefix-material-colors:$versionPlaceholder"
    const val materialLists = "$artifactPrefix-material-lists:$versionPlaceholder"
    const val permissions = "$artifactPrefix-permissions:$versionPlaceholder"
    const val preferences = "$artifactPrefix-preferences:$versionPlaceholder"
    const val resources = "$artifactPrefix-resources:$versionPlaceholder"
    const val snackbar = "$artifactPrefix-snackbar:$versionPlaceholder"
    const val stethoInit = "$artifactPrefix-stetho-init:$versionPlaceholder"
    const val systemservices = "$artifactPrefix-systemservices:$versionPlaceholder"
    const val toast = "$artifactPrefix-toast:$versionPlaceholder"
    const val typesaferecyclerview = "$artifactPrefix-typesaferecyclerview:$versionPlaceholder"
    const val views = "$artifactPrefix-views:$versionPlaceholder"
    const val viewsAppcompat = "$artifactPrefix-views-appcompat:$versionPlaceholder"
    const val viewsCardview = "$artifactPrefix-views-cardview:$versionPlaceholder"
    const val viewsCoroutines = "$artifactPrefix-views-coroutines:$versionPlaceholder"
    const val viewsCoroutinesMaterial = "$artifactPrefix-views-coroutines-material:$versionPlaceholder"
    const val viewsDsl = "$artifactPrefix-views-dsl:$versionPlaceholder"
    const val viewsDslAppcompat = "$artifactPrefix-views-dsl-appcompat:$versionPlaceholder"
    const val viewsDslConstraintlayout = "$artifactPrefix-views-dsl-constraintlayout:$versionPlaceholder"
    const val viewsDslCoordinatorlayout = "$artifactPrefix-views-dsl-coordinatorlayout:$versionPlaceholder"
    const val viewsDslIdePreview = "$artifactPrefix-views-dsl-ide-preview:$versionPlaceholder"
    const val viewsDslMaterial = "$artifactPrefix-views-dsl-material:$versionPlaceholder"
    const val viewsDslRecyclerview = "$artifactPrefix-views-dsl-recyclerview:$versionPlaceholder"
    const val viewsMaterial = "$artifactPrefix-views-material:$versionPlaceholder"
    const val viewsRecyclerview = "$artifactPrefix-views-recyclerview:$versionPlaceholder"
    const val viewsSelectable = "$artifactPrefix-views-selectable:$versionPlaceholder"
    const val viewsSelectableAppcompat = "$artifactPrefix-views-selectable-appcompat:$versionPlaceholder"
    const val viewsSelectableConstraintlayout = "$artifactPrefix-views-selectable-constraintlayout:$versionPlaceholder"

}
