import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val annotation: String = "1.0.0" // available: "1.1.0"

    const val appcompat: String = "1.0.2"

    const val cardview: String = "1.0.0"

    const val constraintlayout: String = "1.1.3"

    const val coordinatorlayout: String = "1.0.0"

    const val androidx_core: String = "1.0.1" // available: "1.0.2"

    const val fragment: String = "1.0.0"

    const val androidx_lifecycle: String = "2.0.0"

    const val recyclerview: String = "1.0.0"

    const val room_runtime: String = "2.0.0" // available: "2.1.0"

    const val espresso_core: String = "3.1.1" // available: "3.2.0"

    const val junit: String = "1.1.0" // available: "1.1.1"

    const val androidx_test_core_ktx: String = "1.1.0" // available: "1.2.0"

    const val androidx_test_runner: String = "1.1.1" // available: "1.2.0"

    const val aapt2: String = "3.5.0-5435860"

    const val lint_gradle: String = "26.5.0"

    const val stetho: String = "1.5.0" // available: "1.5.1"

    const val material: String = "1.0.0"

    const val timber: String = "4.7.1"

    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.4.2"

    const val org_jetbrains_kotlin: String = "1.3.50"

    const val org_jetbrains_kotlinx: String = "1.3.0"

    /**
     *
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "5.6.1"

    const val gradleCurrentVersion: String = "5.6"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
            id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
