import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Deps {
    const val de_fayard_buildsrcversions_gradle_plugin: String =
            "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:0.6.2"

    const val androidx_test_core_ktx: String = "androidx.test:core-ktx:1.1.0"

    const val kotlinx_coroutines_android: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.2.1"

    const val kotlinx_coroutines_core: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.2.1"

    const val kotlinx_coroutines_test: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.2.1"

    const val androidx_test_runner: String = "androidx.test:runner:1.1.1"

    const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:1.3.31"

    const val kotlin_stdlib_common: String = "org.jetbrains.kotlin:kotlin-stdlib-common:1.3.31"

    const val kotlin_stdlib_jdk7: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.31"

    const val kotlin_stdlib_js: String = "org.jetbrains.kotlin:kotlin-stdlib-js:1.3.31"

    const val kotlin_test_junit: String = "org.jetbrains.kotlin:kotlin-test-junit:1.3.31"

    const val lifecycle_common: String = "androidx.lifecycle:lifecycle-common:2.0.0"

    const val lifecycle_extensions: String = "androidx.lifecycle:lifecycle-extensions:2.0.0"

    const val lifecycle_livedata: String = "androidx.lifecycle:lifecycle-livedata:2.0.0"

    const val lifecycle_runtime: String = "androidx.lifecycle:lifecycle-runtime:2.0.0"

    const val lifecycle_viewmodel: String = "androidx.lifecycle:lifecycle-viewmodel:2.0.0"

    const val coordinatorlayout: String = "androidx.coordinatorlayout:coordinatorlayout:1.0.0"

    const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:1.1.3"

    const val androidx_core_core: String = "androidx.core:core:1.0.1"

    const val androidx_core_core_ktx: String = "androidx.core:core-ktx:1.0.1"

    const val espresso_core: String = "androidx.test.espresso:espresso-core:3.1.1"

    const val recyclerview: String = "androidx.recyclerview:recyclerview:1.0.0"

    const val room_runtime: String = "androidx.room:room-runtime:2.0.0"

    const val lint_gradle: String = "com.android.tools.lint:lint-gradle:26.5.0-alpha13"

    const val annotation: String = "androidx.annotation:annotation:1.0.0"

    const val appcompat: String = "androidx.appcompat:appcompat:1.0.2"

    const val cardview: String = "androidx.cardview:cardview:1.0.0"

    const val fragment: String = "androidx.fragment:fragment:1.0.0"

    const val material: String = "com.google.android.material:material:1.0.0"

    const val stetho: String = "com.facebook.stetho:stetho:1.5.0"

    const val timber: String = "com.jakewharton.timber:timber:4.7.1"

    const val aapt2: String = "com.android.tools.build:aapt2:3.5.0-alpha13-5435860"

    const val junit: String = "androidx.test.ext:junit:1.1.0"
}
